//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserSQL.Data.EDMX.TSSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0001_TRANSACTIONS
    {
        public string TCode { get; set; }
        public string Description { get; set; }
        public string Module { get; set; }
        public string Type { get; set; }
        public string FormToCall { get; set; }
        public string FunctionToCall { get; set; }
        public string Arg1 { get; set; }
        public string Arg2 { get; set; }
        public string Arg3 { get; set; }
        public int NumberOfParameters { get; set; }
        public bool CheckPermission { get; set; }
        public bool Visible { get; set; }
        public string Namespace { get; set; }
        public Nullable<int> Modo { get; set; }
    }
}
