//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserSQL.Data.EDMX.TSSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TLogTcode
    {
        public decimal IdLog { get; set; }
        public string Tcode { get; set; }
        public string Username { get; set; }
        public string Computer { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public string IPLog { get; set; }
    }
}
