//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserSQL.Data.EDMX.TSSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSecurityLog
    {
        public int idLog { get; set; }
        public string TCode { get; set; }
        public string Username { get; set; }
        public string Computer { get; set; }
        public string IP { get; set; }
        public string Alert { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
    }
}
