//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserSQL.Data.EDMX.TSSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSecRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TSecRole()
        {
            this.TSecRoleAssignment = new HashSet<TSecRoleAssignment>();
        }
    
        public string RoleName { get; set; }
        public string RoleDescription { get; set; }
        public Nullable<bool> IsTcode { get; set; }
        public Nullable<bool> isFunction { get; set; }
        public bool Activo { get; set; }
        public string Modulo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TSecRoleAssignment> TSecRoleAssignment { get; set; }
    }
}
