//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserSQL.Data.EDMX.TSSecurity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TSecRoleAssignment
    {
        public string idUser { get; set; }
        public string idRole { get; set; }
        public bool idActivo { get; set; }
    
        public virtual TSecRole TSecRole { get; set; }
        public virtual TSecUsr TSecUsr { get; set; }
    }
}
