//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserSQL.Data.EDMX.TSSecurity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TecserDataS : DbContext
    {
        public TecserDataS()
            : base("name=TecserDataS")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T0001_TRANSACTIONS> T0001_TRANSACTIONS { get; set; }
        public virtual DbSet<TLogTcode> TLogTcode { get; set; }
        public virtual DbSet<TSecRole> TSecRole { get; set; }
        public virtual DbSet<TSecRoleAssignment> TSecRoleAssignment { get; set; }
        public virtual DbSet<TSecurityLog> TSecurityLog { get; set; }
        public virtual DbSet<TsecurityLogCheck> TsecurityLogCheck { get; set; }
        public virtual DbSet<TSecUsr> TSecUsr { get; set; }
    }
}
