//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0033_COSTO
    {
        public string MATERIAL { get; set; }
        public Nullable<int> STOCK { get; set; }
        public Nullable<decimal> COSTO_UC_ARS { get; set; }
        public Nullable<decimal> COSTO_UC_USD { get; set; }
        public Nullable<System.DateTime> FECHA_UC { get; set; }
        public Nullable<decimal> COSTO_ARS { get; set; }
        public Nullable<decimal> COSTO_USD { get; set; }
        public Nullable<decimal> COSTO_1_ARS { get; set; }
        public Nullable<decimal> COSTO_1_USD { get; set; }
        public Nullable<decimal> VarCosto_ARS { get; set; }
        public Nullable<decimal> VarCosto_USD { get; set; }
        public Nullable<System.DateTime> UM { get; set; }
        public string MTYPE { get; set; }
        public string FORM { get; set; }
        public string CostDetermination { get; set; }
        public string CostDeterminationBy { get; set; }
        public Nullable<int> Proveedor { get; set; }
        public Nullable<System.DateTime> UltimoCostRoll { get; set; }
        public string Log_UserUPD { get; set; }
        public Nullable<System.DateTime> Log_FechaUPD { get; set; }
        public Nullable<decimal> ValorUSD_ { get; set; }
        public Nullable<decimal> ValorARS_ { get; set; }
        public Nullable<decimal> COSTO_PPP_ARS { get; set; }
        public Nullable<decimal> COSTO_PPP_USD { get; set; }
        public Nullable<bool> AUTO_UPD { get; set; }
        public string MonedaCosto { get; set; }
        public Nullable<decimal> TCConversion { get; set; }
    
        public virtual T0010_MATERIALES T0010_MATERIALES { get; set; }
    }
}
