//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0033_COSTL1
    {
        public string MATERIAL { get; set; }
        public string MATERIAL_ { get; set; }
        public string ORIGEN { get; set; }
        public Nullable<int> LEVEL { get; set; }
        public string MON { get; set; }
        public Nullable<decimal> TC { get; set; }
        public Nullable<decimal> COSTO_ARS { get; set; }
        public Nullable<decimal> COSTO_USD { get; set; }
        public Nullable<int> FORM_ID { get; set; }
        public string COMENT_L0 { get; set; }
        public Nullable<decimal> BASE_F { get; set; }
        public Nullable<decimal> PROP { get; set; }
        public Nullable<decimal> PROP_ARS { get; set; }
        public Nullable<decimal> PROP_USD { get; set; }
        public Nullable<System.DateTime> COST_DATE { get; set; }
    }
}
