//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0135_GLX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0135_GLX()
        {
            this.T0134_GLL4 = new HashSet<T0134_GLL4>();
        }
    
        public string GL { get; set; }
        public string GLX { get; set; }
        public string GLDESC { get; set; }
        public string NIVEL { get; set; }
        public Nullable<bool> IMPU_S { get; set; }
        public Nullable<bool> IMPU_N { get; set; }
        public Nullable<bool> ACTIVA { get; set; }
        public Nullable<bool> IMPU_MANUAL { get; set; }
        public string IDC2 { get; set; }
        public Nullable<bool> REVISION { get; set; }
        public Nullable<int> IdRevision { get; set; }
        public string Disponible { get; set; }
        public Nullable<bool> VisibleGLReport { get; set; }
        public string GLMapX { get; set; }
        public bool GLMapIncluirHijos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0134_GLL4> T0134_GLL4 { get; set; }
    }
}
