//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0205_COBRANZA_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0205_COBRANZA_H()
        {
            this.T0206_COBRANZA_I = new HashSet<T0206_COBRANZA_I>();
        }
    
        public int IDCOB { get; set; }
        public Nullable<int> CLIENTE { get; set; }
        public string NRECIBO { get; set; }
        public string NRECIPROVI { get; set; }
        public string CUENTA { get; set; }
        public string MON { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string ReciboDesc { get; set; }
        public string LogUser { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<bool> CCK { get; set; }
        public Nullable<bool> IMPRESO { get; set; }
        public Nullable<decimal> TC { get; set; }
        public Nullable<bool> DOC_CANCELADO { get; set; }
        public Nullable<bool> DOC_DESIMPUTADO { get; set; }
        public Nullable<int> NASIENTO_R { get; set; }
        public Nullable<int> NASIENTO_C { get; set; }
        public Nullable<int> DIAS_PP { get; set; }
        public Nullable<int> NASIENTO { get; set; }
        public string NRECIBOOFI { get; set; }
        public Nullable<bool> ENVIAREMAIL { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ENVIADO { get; set; }
        public string EMAILMENSAJE { get; set; }
    
        public virtual T0006_MCLIENTES T0006_MCLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0206_COBRANZA_I> T0206_COBRANZA_I { get; set; }
    }
}
