//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0207_SPLITFACTURAS
    {
        public Nullable<int> INTDOC { get; set; }
        public string TDOC { get; set; }
        public int IDCTACTE { get; set; }
        public Nullable<int> IDDOC { get; set; }
        public string NDOC { get; set; }
        public int FACTSPLIT { get; set; }
        public Nullable<System.DateTime> FACT_FECHA { get; set; }
        public string FACT_MONEDA { get; set; }
        public Nullable<decimal> FACT_MONTO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public Nullable<decimal> MONTO_APLICADO { get; set; }
        public string TIPO { get; set; }
        public int CLIENTE { get; set; }
        public Nullable<System.DateTime> FECHA_FACT { get; set; }
        public Nullable<System.DateTime> FECHA_VENC { get; set; }
        public Nullable<int> DIAS_VENC { get; set; }
        public string NRECIBO { get; set; }
        public Nullable<System.DateTime> PFECHA { get; set; }
        public Nullable<int> XLINE { get; set; }
        public string XCK { get; set; }
        public string XCOMENTARIO { get; set; }
        public Nullable<int> ZTERM { get; set; }
        public Nullable<int> IDCOB { get; set; }
        public Nullable<int> IDNC { get; set; }
        public string NumeroDoc { get; set; }
        public string TipoDocCancel { get; set; }
        public Nullable<int> DiasPPCob { get; set; }
        public Nullable<int> DiasImpu { get; set; }
        public Nullable<decimal> USDImpu { get; set; }
    }
}
