//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0300_NCD_H
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T0300_NCD_H()
        {
            this.T0301_NCD_I = new HashSet<T0301_NCD_I>();
        }
    
        public int IDH { get; set; }
        public string TDOC { get; set; }
        public string NDOC { get; set; }
        public string TIPO { get; set; }
        public string MON { get; set; }
        public Nullable<bool> APLICA { get; set; }
        public string APLICA_TDOC { get; set; }
        public string APLICA_DOC { get; set; }
        public Nullable<int> CLINUM { get; set; }
        public string CLITXT { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> TC { get; set; }
        public Nullable<decimal> TOTAL_USD_BRUTO { get; set; }
        public Nullable<decimal> TOTAL_ARS_BRUTO { get; set; }
        public Nullable<decimal> TOTAL_IVA { get; set; }
        public Nullable<decimal> TOTAL_IMPO { get; set; }
        public Nullable<decimal> TOTAL_ARS_NETO { get; set; }
        public Nullable<decimal> TOTAL_USD_NETO { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<int> ASIENTO { get; set; }
        public string LOGUSER { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public Nullable<bool> TEMP { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> SUBTOTAL_ARS { get; set; }
        public Nullable<decimal> IIBB_ALICUOTA { get; set; }
        public string IIBB_TXTDESCRIPCION { get; set; }
        public Nullable<decimal> IIBB_IMPORTE { get; set; }
        public Nullable<int> idFacturaT0400 { get; set; }
        public Nullable<int> idCtaCte { get; set; }
        public Nullable<decimal> idFacturaX { get; set; }
        public string ndoc_old { get; set; }
    
        public virtual T0006_MCLIENTES T0006_MCLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T0301_NCD_I> T0301_NCD_I { get; set; }
    }
}
