//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0506_SYJ_IMPU
    {
        public int ID { get; set; }
        public Nullable<int> SYJID { get; set; }
        public Nullable<int> ITEM { get; set; }
        public string IDEMPLEADO { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<double> PAGADO { get; set; }
        public string COMENTARIO { get; set; }
        public string GLAP { get; set; }
        public string GLPAGO { get; set; }
        public Nullable<double> NAS { get; set; }
        public bool CONTA { get; set; }
        public string LOGUSER { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public Nullable<double> CHID { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    }
}
