//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0505_SYJ_PAYITEMS
    {
        public Nullable<int> SYJID { get; set; }
        public Nullable<int> ITEM { get; set; }
        public string GLCUENTA { get; set; }
        public string GLCUENTA_D { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<int> CHEID { get; set; }
        public string EMPLID { get; set; }
        public bool CONTA { get; set; }
        public Nullable<int> ASIENTO { get; set; }
    }
}
