//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0503_SYJ_I
    {
        public Nullable<int> SYJID { get; set; }
        public string ID { get; set; }
        public string PERIODO { get; set; }
        public string EMPLEADO { get; set; }
        public string GL { get; set; }
        public string QUINCENA { get; set; }
        public string FRECUENCIA { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> PAGADO { get; set; }
        public string TIPO { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<int> NASIENTO { get; set; }
        public string LOGUSER { get; set; }
        public Nullable<System.DateTime> LOGDATE { get; set; }
        public string GLAP { get; set; }
        public bool EMPL { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
    }
}
