//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0502_SYJ_H
    {
        public Nullable<int> SYJID { get; set; }
        public string MES { get; set; }
        public string YEAR { get; set; }
        public string MON { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> PAGADO { get; set; }
        public string REF { get; set; }
        public string COMENTARIO { get; set; }
        public bool COMPLETO { get; set; }
        public Nullable<int> NASIENTO { get; set; }
        public string TIPO { get; set; }
        public string LOG_USER { get; set; }
        public string LOG_DATE { get; set; }
        public Nullable<System.DateTime> FECHA_CONTA { get; set; }
    }
}
