//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecserEF.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T0504_SYJ_PAYTEMP
    {
        public Nullable<int> SYJID { get; set; }
        public string ID { get; set; }
        public string PERIODO { get; set; }
        public string EMPLEADO { get; set; }
        public string CONCEPTO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> PAGADO { get; set; }
        public Nullable<decimal> APAGAR { get; set; }
        public string TIPO { get; set; }
        public string COMENTARIO { get; set; }
        public string GLAP { get; set; }
        public Nullable<double> PENDPAGO { get; set; }
        public string GL { get; set; }
        public bool EMPL { get; set; }
    }
}
